#define ID_TEX_MISC 20


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_GROUND 5
#define OBJECT_TYPE_PIPE 6
#define OBJECT_TYPE_MUSHROOM 7
#define OBJECT_TYPE_FLOWER 8

#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 
